version: '3.3'

services:
  travel-diary-api-server-project:
    image: travel-diary-api-server-project
    container_name: travel-diary-api-server-project
    command: /usr/sbin/apache2ctl -D FOREGROUND
    volumes:
      - ./src/:/var/www/html
    ports:
      - '10022:22'
      - '10080:80'
      - '18080:8080'
    expose:
      - '10022'
      - '10080'
      - '18080'
